#!/bin/bash

export ONED=/mnt/c/Users/hyuns/OneDrive

HS=~/.HS
HS_FUNCTION=~/.HS/Function_HS

alias dir='dir --color=always'
alias rm='rm -i'
alias cp='cp -i'
alias mv='mv -i'
alias py='python3'
alias sphinx='rsh hyunsuk@10.74.16.31'
alias parao='rsh hyunsuk@10.74.16.30'
alias pyramid='rsh hyunsuk@10.74.16.127'

alias merlin='rsh lee_h1@merlin-l-001.psi.ch'
alias merlin002='rsh lee_h1@merlin-l-002.psi.ch'
alias merlin001='rsh lee_h1@merlin-l-001.psi.ch'
mer='lee_h1@merlin-l-002.psi.ch'

alias np='/mnt/c/Program\ Files\ \(x86\)/Notepad++/notepad++.exe'

# source $HS/Path_HS/Path_HS -A export
# source $HS/Alias_HS -A export
# for p in $(ls $HS_FUNCTION)
# do
# echo  $HS_FUNCTION/$p
# source $HS_FUNCTION/$p -A export
# done
# cds_load

export PATH_CDS=/home/hyunsuk/.HS/functions/cds
source $PATH_CDS/load_functions.sh

# export -f gethostfile
# export -f ckprocs
# export -f rps

par="hyunsuk@10.74.16.30"
sph="hyunsuk@10.74.16.31"
pyd="hyunsuk@10.74.16.127"

PS1='${debian_chroot:+($debian_chroot)}\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\W\[\033[00m\]\$ '
export PS1='[$(whoami) ${PWD/*\//}]$ '

export MCS_PATH_XSDIR=$ONED/xslib/MCS
export MCS_XSDIR=xsdir_endf71
export DATAPATH=$ONED/code/MCNP/MCNP_DATA

export PATH=~/bin:$PATH
export PATH=.:$PATH

# export LS_COLORS="$LS_COLORS:ow=1;34:tw=1;34:di=1;33:"
export LS_COLORS="ow=1;34:tw=1;34:di=1;33:"
export LS_COLORS='auto'
# export LS_COLORS="ow=1;34:tw=1;34:di=1;4;31;42:"
test -r profiles/.dir_colors && eval $(dircolors profiles/.dir_colors)


#
# dir_colors file is taken from  https://github.com/arcticicestudio/nord-dircolors.git
# link this fi  ln -sr "$PWD/src/dir_colors" ~/.dir_colors
